apiVersion: v1
clusters:
- cluster:
    extensions:
    - extension:
        last-update: Mon, 03 Nov 2025 13:17:44 IST
        provider: minikube.sigs.k8s.io
        version: v1.17.1
      name: cluster_info
    # CRITICAL: The corrected port is here!
    server: https://host.docker.internal:60779 
    insecure-skip-tls-verify: true 
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 03 Nov 2025 13:17:44 IST
        provider: minikube.sigs.k8s.io
        version: v1.17.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user: {} # We leave this empty because Jenkins uses insecure-skip-tls-verify=true